### PR TITLE
convert client to es6 class and add babel for backwards compatibility

### PR DESCRIPTION
**Pull request by krazyjakee**
tests are passing for node v0.10.32

### CODE REVIEW

**Comment by krazyjakee** [comment]
#8 

I rarely do pull requests so I hope everything is in order here.

**Comment by h2non** [comment]
That's a good start. We could take the advantage of more ES6 features, such as arrow function expressions, promises, destructuring and so on, but don't feel forced to do it.

I would like to proceed with the merge if that's ok for you.

**Comment by krazyjakee** [comment]
I agree and will progress the code update.

Travis says that the latest stable build (v7.0) failed but locally I am having no issues with that build.

With that in mind, I'll leave it up to you if you'd like to merge :)

**Comment by h2non** [comment]
The Travis issue is related to an `npm` error, but not quite sure why. In any case, `lodash` was only a dev dependency and not used anymore, so I removed it. That should fix the issue.

**Pull request merged**
